# Generated by Django 4.2.11 on 2026-01-28 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
            options={
                'db_table': 'conferences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'venues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('school', models.CharField(db_index=True, max_length=200)),
                ('mascot', models.CharField(blank=True, max_length=100)),
                ('abbreviation', models.CharField(blank=True, db_index=True, max_length=20)),
                ('display_name', models.CharField(max_length=200)),
                ('short_display_name', models.CharField(blank=True, max_length=100)),
                ('primary_color', models.CharField(blank=True, max_length=10)),
                ('secondary_color', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='basketball.conference')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='basketball.venue')),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['school'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncaa_game_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('final', 'Final'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('status_detail', models.CharField(blank=True, max_length=100)),
                ('season', models.IntegerField(db_index=True)),
                ('season_type', models.CharField(choices=[('regular', 'Regular Season'), ('postseason', 'Postseason'), ('preseason', 'Preseason')], default='regular', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='basketball.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='basketball.team')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='basketball.venue')),
            ],
            options={
                'db_table': 'games',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(db_index=True)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('conference_wins', models.IntegerField(default=0)),
                ('conference_losses', models.IntegerField(default=0)),
                ('points_per_game', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('points_allowed_per_game', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('field_goal_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('three_point_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('free_throw_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('rebounds_per_game', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('offensive_rebounds_per_game', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('defensive_rebounds_per_game', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assists_per_game', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('steals_per_game', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blocks_per_game', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('turnovers_per_game', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='basketball.team')),
            ],
            options={
                'db_table': 'team_stats',
                'ordering': ['-season', 'team__school'],
                'indexes': [models.Index(fields=['season'], name='team_stats_season_594a9d_idx')],
                'unique_together': {('team', 'season')},
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['school'], name='teams_school_3dc45d_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['abbreviation'], name='teams_abbrevi_be252d_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['source_id'], name='teams_source__8beea3_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['date'], name='games_date_02ed81_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['season'], name='games_season_e71dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status'], name='games_status_def24c_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['ncaa_game_id'], name='games_ncaa_ga_6e786b_idx'),
        ),
    ]
