# Generated by Django 4.2.11 on 2026-01-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ncaa_slug',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['ncaa_slug'], name='teams_ncaa_sl_d74c9f_idx'),
        ),
    ]
