# Generated by Django 4.2.11 on 2026-01-28 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_supabase_users_supabase_user_id_idx_supabase_us_supabas_fbac80_idx_and_more'),
        ('basketball', '0002_team_ncaa_slug_team_teams_ncaa_sl_d74c9f_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchupPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(blank=True, db_index=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='basketball.game')),
                ('predicted_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_wins', to='basketball.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='authentication.supabaseuser')),
            ],
            options={
                'db_table': 'matchup_predictions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='matchup_pre_user_id_43b434_idx'), models.Index(fields=['game'], name='matchup_pre_game_id_10fb68_idx'), models.Index(fields=['is_correct'], name='matchup_pre_is_corr_434e25_idx'), models.Index(fields=['user', 'is_correct'], name='matchup_pre_user_id_b4837a_idx')],
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='basketball.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_teams', to='authentication.supabaseuser')),
            ],
            options={
                'db_table': 'favorite_teams',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='favorite_te_user_id_d99cd7_idx'), models.Index(fields=['team'], name='favorite_te_team_id_67d487_idx')],
                'unique_together': {('user', 'team')},
            },
        ),
    ]
