# Generated by Django 4.2.11 on 2026-01-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0005_ml_prediction_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kenpomrating',
            name='event',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
