# Generated by Django 4.2.11 on 2026-01-29 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0006_fix_event_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncaa_player_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('jersey_number', models.CharField(blank=True, max_length=5)),
                ('position', models.CharField(blank=True, choices=[('G', 'Guard'), ('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('F', 'Forward'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center'), ('G/F', 'Guard/Forward'), ('F/C', 'Forward/Center')], max_length=10)),
                ('height', models.CharField(blank=True, max_length=10)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('year', models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=5)),
                ('season', models.IntegerField(default=2026)),
                ('is_active', models.BooleanField(default=True)),
                ('is_starter', models.BooleanField(default=False)),
                ('is_key_player', models.BooleanField(default=False)),
                ('avg_minutes', models.FloatField(blank=True, null=True)),
                ('avg_points', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='basketball.team')),
            ],
            options={
                'db_table': 'players',
                'ordering': ['team', '-avg_minutes'],
            },
        ),
        migrations.CreateModel(
            name='InjuryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OUT', 'Out'), ('DOUBTFUL', 'Doubtful'), ('QUESTIONABLE', 'Questionable'), ('PROBABLE', 'Probable'), ('AVAILABLE', 'Available'), ('DAY_TO_DAY', 'Day-to-Day')], max_length=20)),
                ('injury_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('detection_method', models.CharField(choices=[('OFFICIAL', 'Official Report'), ('MINUTES_DROP', 'Minutes Drop Detection'), ('DNP', 'Did Not Play'), ('MANUAL', 'Manual Entry')], default='MANUAL', max_length=20)),
                ('reported_date', models.DateField()),
                ('expected_return', models.DateField(blank=True, null=True)),
                ('actual_return', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('impact_score', models.FloatField(blank=True, null=True)),
                ('minutes_before_injury', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_injuries', to='basketball.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='basketball.player')),
            ],
            options={
                'db_table': 'injury_reports',
                'ordering': ['-reported_date', '-impact_score'],
            },
        ),
        migrations.CreateModel(
            name='TeamSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('games_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('total_points_allowed', models.IntegerField(default=0)),
                ('field_goals_made', models.IntegerField(default=0)),
                ('field_goals_attempted', models.IntegerField(default=0)),
                ('three_pointers_made', models.IntegerField(default=0)),
                ('three_pointers_attempted', models.IntegerField(default=0)),
                ('free_throws_made', models.IntegerField(default=0)),
                ('free_throws_attempted', models.IntegerField(default=0)),
                ('offensive_rebounds', models.IntegerField(default=0)),
                ('defensive_rebounds', models.IntegerField(default=0)),
                ('total_rebounds', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('turnovers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_season_stats', to='basketball.team')),
            ],
            options={
                'db_table': 'team_season_stats',
                'ordering': ['-season', 'team__school'],
                'unique_together': {('team', 'season')},
            },
        ),
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(default=0)),
                ('started', models.BooleanField(default=False)),
                ('dnp', models.BooleanField(default=False)),
                ('dnp_reason', models.CharField(blank=True, max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('field_goals_made', models.IntegerField(default=0)),
                ('field_goals_attempted', models.IntegerField(default=0)),
                ('three_pointers_made', models.IntegerField(default=0)),
                ('three_pointers_attempted', models.IntegerField(default=0)),
                ('free_throws_made', models.IntegerField(default=0)),
                ('free_throws_attempted', models.IntegerField(default=0)),
                ('offensive_rebounds', models.IntegerField(default=0)),
                ('defensive_rebounds', models.IntegerField(default=0)),
                ('total_rebounds', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('turnovers', models.IntegerField(default=0)),
                ('fouls', models.IntegerField(default=0)),
                ('plus_minus', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='basketball.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='basketball.player')),
            ],
            options={
                'db_table': 'player_game_stats',
                'ordering': ['-game__date', '-minutes'],
                'indexes': [models.Index(fields=['player', 'game'], name='player_game_player__a93cea_idx'), models.Index(fields=['game', '-minutes'], name='player_game_game_id_2feee7_idx')],
                'unique_together': {('player', 'game')},
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team', 'season'], name='players_team_id_1805b9_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['ncaa_player_id'], name='players_ncaa_pl_039334_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['last_name', 'first_name'], name='players_last_na_1ee9ea_idx'),
        ),
        migrations.AddIndex(
            model_name='injuryreport',
            index=models.Index(fields=['player', 'is_active'], name='injury_repo_player__a3e429_idx'),
        ),
        migrations.AddIndex(
            model_name='injuryreport',
            index=models.Index(fields=['reported_date'], name='injury_repo_reporte_d54f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='injuryreport',
            index=models.Index(fields=['status', 'is_active'], name='injury_repo_status_15b33f_idx'),
        ),
    ]
