# Generated by Django 4.2.11 on 2026-01-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupabaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_user_id', models.UUIDField(unique=True, db_index=True)),
                ('email', models.EmailField(max_length=255)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], db_index=True, default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supabase User',
                'verbose_name_plural': 'Supabase Users',
                'db_table': 'supabase_users',
                'indexes': [
                    models.Index(fields=['supabase_user_id'], name='supabase_users_supabase_user_id_idx'),
                    models.Index(fields=['email'], name='supabase_users_email_idx'),
                    models.Index(fields=['role'], name='supabase_users_role_idx'),
                ],
            },
        ),
    ]
