# Generated by Django 4.2.11 on 2026-01-07 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supabaseuser',
            new_name='supabase_us_supabas_fbac80_idx',
            old_name='supabase_users_supabase_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='supabaseuser',
            new_name='supabase_us_email_8d2eac_idx',
            old_name='supabase_users_email_idx',
        ),
        migrations.RenameIndex(
            model_name='supabaseuser',
            new_name='supabase_us_role_96ef4d_idx',
            old_name='supabase_users_role_idx',
        ),
    ]
